name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        node-version: [16.x]
        redis: [5.x]
    name: CI - redis ${{ matrix.redis }}, node ${{ matrix.node-version }}
    steps:
    - name: setup redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: ${{ matrix.redis }}
    - name: ping redis
      run: redis-cli ping
    - name: checkout main repo
      uses: actions/checkout@v3
    - name: checkout openupm/openupm repo for the data folder
      uses: actions/checkout@v3
      with:
        repository: openupm/openupm
        ref: master
        path: tmp-openupm
    - name: move tmp-openupm/data to data
      run: mv tmp-openupm/data data && rm -rf tmp-openupm
    - name: set node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 3
        max_attempts: 3
        command: npm install
    - name: npm run test
      run: npm run test

  build-website-us:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.repository == 'openupm/openupm-next'
    steps:
    - name: checkout main repo
      uses: actions/checkout@v3
    - name: checkout openupm/openupm repo for the data folder
      uses: actions/checkout@v3
      with:
        repository: openupm/openupm
        ref: master
        path: tmp-openupm
    - name: move tmp-openupm/data to data
      run: mv tmp-openupm/data data && rm -rf tmp-openupm
    - name: set node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: npm install
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 3
        max_attempts: 3
        command: npm install
    - name: npm run docs:build
      run: VITE_OPENUPM_REGION=us npm run docs:build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bundle-analysis-report
        path: bundle-analyse.html
    - name: deploy to openupm-next-website repo
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        repository-name: openupm/openupm-next-website
        folder: docs/.vuepress/dist
        single-commit: true
        ssh-key: ${{ secrets.OPENUPM_NEXT_WEBSITE_DEPLOY_KEY }}
